[libraries]
assertj-core = { group = "org.assertj", name = "assertj-core", version = "3.27.6" }
archunit-junit5-api = { group = "com.tngtech.archunit", name = "archunit-junit5-api", version = "1.4.1" }
camel-quarkus-jackson = { group = "org.apache.camel.quarkus", name = "camel-quarkus-jackson", version = "3.29.0" }
commons-vfs2 = { group = "org.apache.commons", name = "commons-vfs2", version = "2.10.0" }
graal = { group = "org.graalvm.nativeimage", name = "svm", version = "25.0.1" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version = "1.6.3" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version = "1.6.3" }
mongock-bom = { group = "io.mongock", name = "mongock-bom", version = "5.5.1" }
jboss-vfs = { group = "org.jboss", name = "jboss-vfs", version = "3.3.2.Final" }
quarkus-resteasy-problem = { group = "com.tietoevry.quarkus", name = "quarkus-resteasy-problem", version = "3.9.0" }
wiremock = { group = "com.github.tomakehurst", name = "wiremock-jre8", version = "3.0.1" }
testcontainers-keycloak = { group = "com.github.dasniko", name = "testcontainers-keycloak", version = "4.0.0" }
checkstyle = { module = "com.puppycrawl.tools:checkstyle", version = "12.1.2" }

[plugins]
gradle-git-properties = { id = "com.gorylenko.gradle-git-properties", version = "2.5.3" }
gradle-node = { id = "com.github.node-gradle.node", version = "7.1.0" }
liquibase = { id = "org.liquibase.gradle", version = "3.0.2" }
liquibase_core = { group = 'org.liquibase', id = "liquibase-core", version = "4.27.0" }
sonarqube = { id = "org.sonarqube", version = "7.0.1.6134" }
openapi-generator = { id = "org.openapi.generator", version = "7.17.0" }
no-http-checkstyle = { id = "io.github.checkstyle.checkstyle", version = "0.0.11" }
modernizer = { id = "org.gaul.modernizer", version = "1.8.0" }
