[libraries]
assertj-core = { group = "org.assertj", name = "assertj-core", version = "3.26.3" }
archunit-junit5-api = { group = "com.tngtech.archunit", name = "archunit-junit5-api", version = "1.3.0" }
camel-quarkus-jackson = { group = "org.apache.camel.quarkus", name = "camel-quarkus-jackson", version = "3.15.0" }
commons-vfs2 = { group = "org.apache.commons", name = "commons-vfs2", version = "2.9.0" }
graal = { group = "org.graalvm.nativeimage", name = "svm", version = "24.1.0" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version = "1.6.2" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version = "1.6.2" }
mongock-bom = { group = "com.github.cloudyrock.mongock", name = "mongock-bom", version = "4.3.8" }
quarkus-resteasy-problem = { group = "com.tietoevry.quarkus", name = "quarkus-resteasy-problem", version = "3.9.0" }
wiremock = { group = "com.github.tomakehurst", name = "wiremock-jre8", version = "3.0.1" }
testcontainers-keycloak = { group = "com.github.dasniko", name = "testcontainers-keycloak", version = "3.5.0" }
checkstyle = { module = "com.puppycrawl.tools:checkstyle", version = "10.18.2" }

[plugins]
gradle-git-properties = { id = "com.gorylenko.gradle-git-properties", version = "2.4.2" }
gradle-node = { id = "com.github.node-gradle.node", version = "7.1.0" }
liquibase = { id = "org.liquibase.gradle", version = "2.2.0" }
sonarqube = { id = "org.sonarqube", version = "5.1.0.4882" }
openapi-generator = { id = "org.openapi.generator", version = "7.9.0" }
no-http-checkstyle = { id = "io.github.checkstyle.checkstyle", version = "0.0.11" }
modernizer = { id = "org.gaul.modernizer", version = "1.8.0" }
